<section class="banner banner__footer">
	<div class="banner__content">
		<p class="banner__title">플레이디와 함께 멈추지 않는 성장을 경험하세요.</p>
		<div class="button__wrap">
			<a href="#" class="button button__radius button__lined-white">프로젝트 문의하기</a>
			<a href="#" class="button button__radius button__filled-white">회사 소개서 다운로드</a><!-- 20220628 //-->
		</div>
	</div>
</section>
<footer class="footer">
	<div class="footer-top">
		<div class="footer-top__inner">
			<a href="#" class="logo logo__footer"><span class="a11y">플레이디</span></a>
			<ul class="footer__nav">
				<li><a href="#">윤리신고</a></li>
				<li><a href="#">뉴스레터</a></li>
				<li><a href="#">오시는 길</a></li><!-- 20220628 //-->
				<li><a href="#">무료 광고 진단</a></li><!-- 20220628 //-->
				<li><a href="./personal.html">개인정보처리방침</a></li><!-- 220701 //-->
			</ul>
			<nav class="footer__nav--right">
				<a href="#" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-naver.png" /><span class="a11y">네이버</span></a>
				<a href="#" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-instagram.png" /><span class="a11y">인스타그램</span></a>
				<a href="#" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-youtube.png" /><span class="a11y">유투브</span></a>
				<a href="#" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-facebook.png" /><span class="a11y">페이스북</span></a>
			</nav>
		</div>
	</div>
	<div class="footer-bottom">
		<ul class="footer__util">
			<li>(주)플레이디</li>
			<li>대표자 : 이준용 | 사업자등록번호 : 129-86-43885</li>
			<li>주소 : 경기도 성남시 분당구 황새울로 359번길 11, 5층</li>
			<li>이메일 : <a href="mailto:master@playd.com">master@playd.com</a></li>
			<li class="copyright">Copyright &copy; PlayD.,Ltd, All rights reserved.</li>
		</ul>
		<nav class="footer__util--right">
			<p class="information"><span class="information__title">대표전화</span>1566-3265</p>
			<ul class="information__desc">
				<li>MON - FRI 09 : 00 - 18:00</li>
				<li>주말, 공휴일 휴무</li>
				<li>BREAK TIME : 12:30 - 13:30</li>
			</ul>
		</nav>
	</div>
</footer>

<!-- 20220617 s -->
<div class="layer__body popup newsLetter" id="newsLetter" aria-hidden="true" role="dialog">
  <div class="layer__wrap layer__wrap--full">
		<div class="layer__close">
			<button class="close"><span>close</span></button>
		</div>
		<div class="layer__inner">
			<div class="layer__head">
				<p class="content__title">PlayD 뉴스레터 신청</p>
			</div>
			<div class="layer__content">
				<div class="content__text">
					<p class="content__description">광고·마케팅과 관련한 최근 미디어 이슈부터, 트렌드, 인사이트 리포트까지 뉴스레터로 손쉽게 받아보세요.</p>
					<form action=''>
						<legend>플레이디 뉴스레터 신청폼</legend>
						<div class="input-box input-box--info">
							<div class="form-field">
								<label for="user-name" class="input-box--info__label input-box--info__label--necessary">이름</label>
								<input type="text" id="user-name"  class="input-box--info__input" name="" placeholder="이름을 입력해 주세요.">
								<p class="form-warning">이름을 입력해주세요.</p>
							</div>
							<div class="form-field">
								<label for="user-profession" class="input-box--info__label input-box--info__label--necessary">직업</label>
								<input type="text" id="user-profession" class="input-box--info__input" name="" placeholder="직업을 입력해 주세요.">
								<p class="form-warning">직업을 입력해 주세요.</p>
							</div>
							<div class="form-field">
								<label for="user-mail" class="input-box--info__label input-box--info__label--necessary">이메일 주소</label>
								<input type="text" id="user-mail"  class="input-box--info__input" name="" placeholder="이메일 주소를 입력해 주세요.">
								<p class="form-warning">이메일 주소를 입력해 주세요.</p>
							</div>
							<div class="form-field">
								<label for="user-position" class="input-box--info__label">직급</label>
								<input type="text" id="user-position" class="input-box--info__input" name="" placeholder="직급을 입력해 주세요.">
							</div>
							<div class="form-field">
								<label for="user-company" class="input-box--info__label">회사명(소속)</label>
								<input type="text" id="user-company" class="input-box--info__input" name="" placeholder="회사명(소속)을 입력해 주세요.">
							</div>
							<div class="form-field">
								<label for="user-team" class="input-box--info__label">부서(팀명)</label>
								<input type="text" id="user-team" class="input-box--info__input" name="" placeholder="부서(팀명)을 입력해 주세요.">
							</div>
							<ol class="sub-checkboxs">
                <li class="sub-checkbox__list">
                  <label for="sub-checkbox--personal" class="sub-checkbox__label">
                    <input type="checkbox" id="sub-checkbox--personal" name="" class="sub-checkbox__input">
                    <span><i></i>개인 정보 수집 및 이용에 동의합니다.</span><!-- 20220628 //-->
                  </label>
                </li>
              </ol>
							<p class="form-description">
								입력하신 이름, 직업, 이메일 주소, 직급, 회사명
								(소속), 부서(팀명)은 뉴스레터 발송을 위해 정보주체로부터 개인 정보를 수집 시에 동의 받은 개인 정보 
								보유, 이용 기간 동안 보관 및 이용됩니다.
							</p><!-- 20220628 //-->
						</div>
					</form>
				</div>
				<div class="button__wrap">
					<input type="submit" class="button layer__button form-submit" value="확인" />
				</div>
			</div>
		</div>
	</div>
</div>
<div class="layer__body popup form-popup letterFormSubmitted" id="letterFormSubmitted" aria-hidden="true" role="dialog">
  <div class="layer__wrap">
    <div class="layer__inner">
      <div class="layer__content">
        <p class="message__title"><span class="icon icon__check"><i></i></span>뉴스레터 신청이 완료되었습니다.</p>
        <p class="message__text">플레이디 뉴스레터를 구독해주셔서 감사합니다.</p>
        <button class="button layer__button close">확인</button>
      </div>
    </div>
  </div>
</div>
<!--// 20220617 e -->

<script src="@@webroot/assets/js/w/swiper.min.js"></script>
<script src="@@webroot/assets/js/w/ui.js"></script>
<!-- s 20220628 -->
<script src="@@webroot/assets/js/jquery-1.12.4.min.js"></script>
<script src="@@webroot/assets/js/jquery-ui-1.13.1.js"></script>
<script src="@@webroot/assets/js/datepicker.js"></script>
<!--// e 20220628 -->
