<footer class="footer">
	<div class="footer-top">
		<div class="footer-top__inner">
			<a href="#" class="logo logo__footer"><span class="a11y">플레이디</span></a>
			<ul class="footer__nav">
				<li><a href="#">윤리신고</a></li>
				<li><a href="#">뉴스레터</a></li>
				<li><a href="#">오시는길</a></li>
				<li><a href="#">무료광고진단</a></li>
				<li><a href="#">개인정보처리방침</a></li>
			</ul>
			<nav class="footer__nav--right">
				<a href="#" class="sns-link"><img src="../../assets/images/common/icons/footer_sns-naver.png" /><span class="a11y">네이버</span></a>
				<a href="#" class="sns-link"><img src="../../assets/images/common/icons/footer_sns-instagram.png" /><span class="a11y">인스타그램</span></a>
				<a href="#" class="sns-link"><img src="../../assets/images/common/icons/footer_sns-youtube.png" /><span class="a11y">유투브</span></a>
				<a href="#" class="sns-link"><img src="../../assets/images/common/icons/footer_sns-facebook.png" /><span class="a11y">페이스북</span></a>
			</nav>
		</div>
	</div>
	<div class="footer-bottom">
		<ul class="footer__util">
			<li>(주)플레이디</li>
			<li>대표자 : 이준용 | 사업자등록번호 : 129-86-43885</li>
			<li>주소 : 경기도 성남시 분당구 황새울로 359번길 11, 5층</li>
			<li>이메일 : <a href="mailto:master@playd.com">master@playd.com</a></li>
			<li class="copyright">Copyright &copy; PlayD.,Ltd, All rights reserved.</li>
		</ul>
		<nav class="footer__util--right">
			<p class="information"><span class="information__title">대표전화</span>1566-3265</p>
			<ul class="information__desc">
				<li>MON - FRI 09 : 00 - 18:00</li>
				<li>주말, 공휴일 휴무</li>
				<li>BREAK TIME : 12:30 - 13:30</li>
			</ul>
		</nav>
	</div>
</footer>
<script src="@@webroot/assets/js/w/ui.js"></script>