<section class="banner banner__footer">
	<div class="banner__content">
		<p class="banner__title">플레이디와 함께 멈추지 않는 성장을 경험하세요.</p>
		<div class="button__wrap">
			<a href="#" class="button button__radius button__lined-white">프로젝트 문의</a><!-- 20220726 //-->
			<a href="#" class="button button__radius button__filled-white">회사 소개서 다운로드</a><!-- 20220628 //-->
		</div>
	</div>
</section>
<footer class="footer">
	<div class="footer-top">
		<div class="footer-top__inner">
			<a href="#" class="logo logo__footer"><span class="a11y">플레이디</span></a>
			<ul class="footer__nav">
				<li><a href="#">윤리위반신고</a></li><!-- 20220726 //-->
				<li><a href="#">뉴스레터</a></li>
				<li><a href="#">오시는 길</a></li><!-- 20220628 //-->
				<li><a href="https://sensen.techhub.co.kr/apply/diagnosis">무료 광고 진단</a></li><!-- 20220628 //--><!-- 20220718 //--> 
				<li><a href="./personal.html">개인정보처리방침</a></li><!-- 220701 //-->
			</ul>
			<nav class="footer__nav--right">
				<a href="https://blog.naver.com/playd_log" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-naverblog.png" /><span class="a11y">네이버</span></a><!-- 20220726 //-->
				<a href="#" class="sns-link"><img src="../assets/images/w/common/icons/footer_sns-instagram.png" /><span class="a11y">인스타그램</span></a>
				<a href="https://pletter.stibee.com/" target="_blank" class="sns-link sns-link--platter"><img src="../assets/images/w/common/icons/footer_sns-platter.png" /><span class="a11y">플레터</span></a><!-- 20240126 -->
			</nav>
		</div>
	</div>
	<div class="footer-bottom">
		<ul class="footer__util">
			<li>(주)플레이디</li>
			<li>대표자 : 이준용 | 사업자등록번호 : 129-86-43885</li>
			<li>주소 : 경기도 성남시 분당구 황새울로 359번길 11, 5~6층</li><!-- 20220726 //-->
			<li>이메일 : <a href="mailto:master@playd.com">master@playd.com</a></li>
			<li class="copyright">Copyright &copy; PlayD.,Ltd, All rights reserved.</li>
		</ul>
		<nav class="footer__util--right">
			<p class="information"><span class="information__title">대표전화</span>1566-3265</p>
			<!-- 20220812 추가 -->
			<ul class="information__desc">
				<li>평일 10:00~17:00</li>
			</ul>
			<!--// 20220812 추가 -->
			<!-- 20220718 //
			<ul class="information__desc">
				<li>MON - FRI 09 : 00 - 18:00</li>
				<li>주말, 공휴일 휴무</li>
				<li>BREAK TIME : 12:30 - 13:30</li>
			</ul> -->
		</nav>
	</div>
</footer>

<!-- s 20220701 수정 -->
<div class="top-button">
	<a href="/"><span class="a11y">위로가기</span></a>
</div>
<!--// e 20220701 수정 -->

<!-- 20220701 레이어팝업 삭제 //-->

<script src="@@webroot/assets/js/w/swiper.min.js"></script>
<script src="@@webroot/assets/js/w/ui.js"></script>
<!-- s 20220628 -->
<script src="@@webroot/assets/js/jquery-1.12.4.min.js"></script>
<script src="@@webroot/assets/js/jquery-ui-1.13.1.js"></script>
<script src="@@webroot/assets/js/datepicker.js"></script>
<!--// e 20220628 -->
<!-- Footer Logscript  Start -------------------------------------------------------------------------------------------------------->	
<!--------- 삭제 금지 : PlayD TERA Log Script v1.2 -->
<script>
var _nSA=(function(_g,_s,_p,_d,_i,_h){ 
 if(_i.wgc!=_g){_i.wgc=_g;_i.wrd=(new Date().getTime());
 var _sc=_d.createElement('script');_sc.src=_p+'//sas.techhub.co.kr/'+_s+'gc='+_g+'&rd='+_i.wrd;
 var _sm=_d.getElementsByTagName('script')[0];_sm.parentNode.insertBefore(_sc, _sm);} return _i;
})('TR9947105674','sa-w.js?',location.protocol,document,window._nSA||{},location.hostname);
</script>
<!--------- 삭제 금지 : PlayD TERA Log Script v1.2 -->
<!-- 채널톡 -->
<script>
  (function(){var w=window;if(w.ChannelIO){return w.console.error("ChannelIO script included twice.");}var ch=function(){ch.c(arguments);};ch.q=[];ch.c=function(args){ch.q.push(args);};w.ChannelIO=ch;function l(){if(w.ChannelIOInitialized){return;}w.ChannelIOInitialized=true;var s=document.createElement("script");s.type="text/javascript";s.async=true;s.src="https://cdn.channel.io/plugin/ch-plugin-web.js";var x=document.getElementsByTagName("script")[0];if(x.parentNode){x.parentNode.insertBefore(s,x);}}if(document.readyState==="complete"){l();}else{w.addEventListener("DOMContentLoaded",l);w.addEventListener("load",l);}})();

  ChannelIO('boot', {
    "pluginKey": "3c1abb65-3b7e-4562-a85e-6ca7f57d0c15"
  });
</script>
<!-- Footer Logscript  END -------------------------------------------------------------------------------------------------------->