<header id="header" class="header @@headertype">
	<div class="header__inner header__inner--full">
		<h1 class="header__title">
			<a href="#" class="logo logo__default">플레이디<span class="a11y">플레이디</span></a>
		</h1>
		<nav class="gnb">
			<div class="gnb__list"><span class="gnb__list--link">사업영역</span></div>
      <div class="gnb__list"><span class="gnb__list--link">솔루션</span></div>
      <div class="gnb__list"><span class="gnb__list--link">인사이트</span></div>
      <div class="gnb__list"><span class="gnb__list--link">플레이디</span></div>
      <div class="gnb__list"><span class="gnb__list--link">CONTACT</span></div>
		</nav>
	</div>
</header>