<header id="header" class="header @@headertype">
	<div class="header__inner">
		<h1 class="header__title">
			<a href="#" class="logo @@logotype"><span class="a11y">플레이디</span></a>
		</h1>
		<nav class="nav">
			<div class="nav__link"><a href="#">사업영역</a></div>
      <div class="nav__link"><a href="#">솔루션</a></div>
      <div class="nav__link"><a href="#">인사이트</a></div>
      <div class="nav__link"><a href="#">플레이디</a></div>
      <div class="nav__link"><a href="./recruit.html">인재채용</a></div>
      <div class="nav__link"><a href="./contact.html">CONTACT</a></div>
      <div class="nav__gnb"><a href="#" type="button"><i></i></a></div>
		</nav>
	</div>
	<div class="navmenu">
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="#">캠페인 전략</a></div>
			<div class="navmenu__link"><a href="#">미디어 전략</a></div>
			<div class="navmenu__link"><a href="#">크리에이티브</a></div>
			<div class="navmenu__link"><a href="#">포트폴리오</a></div>
			<div class="navmenu__link"><a href="#">수상내역</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="#">Tech HUB</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="#">뉴스레터</a></div>
			<div class="navmenu__link"><a href="#">리포트</a></div>
			<div class="navmenu__link"><a href="#">광고컬럼</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="#">ABOUT</a></div>
			<div class="navmenu__link"><a href="#">IR</a></div>
			<div class="navmenu__link"><a href="#">윤리경영</a></div>
			<div class="navmenu__link"><a href="#">ESG</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="#">채용</a></div>
			<div class="navmenu__link"><a href="#">복리후생</a></div>
		</div>
		<div class="navmenu__list" style="display:none;"></div>
	</div>
</header>
<style>
.header__sticked .nav__link:nth-child(@@located) a[type="button"] { color: #EA2126; }	
.header__sticked .nav__link:nth-child(@@located) a[type="button"]::after { content: ''; position: absolute; bottom: -1.5px; left: 0; right: 0; width: 100%; height: 4px; background-color: #EA2126; }
</style>