<header id="header" class="header @@headertype">
	<div class="header__inner">
		<h1 class="header__title" tabindex="0">
			<a href="./index.html" class="logo @@logotype"><span class="a11y">플레이디</span></a>
		</h1>
		<nav class="nav">
			<div @@if (located==='1') { class="nav__link nav__active" } @@if (located!=='1') { class="nav__link" }><a href="./campaign.html">사업영역</a></div>
      <div @@if (located==='2') { class="nav__link nav__active" } @@if (located!=='2') { class="nav__link" }><a href="./techhub.html">솔루션</a></div>
      <div @@if (located==='3') { class="nav__link nav__active" } @@if (located!=='3') { class="nav__link" }><a href="./letter.html">인사이트</a></div>
      <div @@if (located==='4') { class="nav__link nav__active" } @@if (located!=='4') { class="nav__link" }><a href="./about.html">플레이디</a></div>
      <div @@if (located==='5') { class="nav__link nav__active" } @@if (located!=='5') { class="nav__link" }><a href="./contact.html">CONTACT</a></div>
      <div class="nav__gnb"><a href="#" type="button"><i></i></a></div>
		</nav>
	</div>
	<div class="navmenu">
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="./campaign.html">캠페인 전략</a></div>
			<div class="navmenu__link"><a href="./media.html">미디어 전략</a></div> <!-- 20220615 -->
			<div class="navmenu__link"><a href="./creative.html">크리에이티브</a></div> <!-- 20220615 -->
			<div class="navmenu__link"><a href="./portfolio.html">포트폴리오</a></div>
			<div class="navmenu__link"><a href="./awards.html">수상내역</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="./techhub.html">tech HUB</a></div><!-- 20220726 //-->
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="./letter.html">뉴스레터</a></div>
			<div class="navmenu__link"><a href="./report.html">리포트</a></div>
			<div class="navmenu__link"><a href="./column.html">광고컬럼</a></div>
		</div>
		<div class="navmenu__list">
			<div class="navmenu__link"><a href="./about.html">ABOUT</a></div> <!-- 20220615 -->
			<div class="navmenu__link"><a href="./ir.html">IR</a></div>
			<div class="navmenu__link"><a href="./ethical.html">윤리경영</a></div>
			<div class="navmenu__link"><a href="./esg.html">ESG</a></div> <!-- 20220615 -->
		</div>
		<div class="navmenu__list" style="display:none;" tabindex="-1"></div>
	</div>
</header>
<div id="sitemap" class="sitemap">
	<div class="sitemap__inner">
		<h1 class="sitemap__title">
			<a href="./index.html" class="logo logo__default"><span class="a11y">플레이디</span></a>
		</h1>
		<div class="sitemap__close"><button type="button" tabindex="0"><i></i></button></div>
	</div>
	<div class="gnb">
		<ul class="menu">
			<li class="menu__title"><span>사업영역</span></li>
			<li class="menu__link"><a href="./campaign.html"><span>캠페인전략</span></a></li>
			<li class="menu__link"><a href="./media.html"><span>미디어전략</span></a></li> <!-- 20220615 -->
			<li class="menu__link"><a href="./creative.html"><span>크리에이티브</span></a></li> <!-- 20220615 -->
			<li class="menu__link"><a href="./portfolio.html"><span>포트폴리오</span></a></li>
			<li class="menu__link"><a href="./awards.html"><span>수상내역</span></a></li>
		</ul>
		<ul class="menu">
			<li class="menu__title"><span>솔루션</span></li>
			<li class="menu__link"><a href="./techhub.html"><span>tech HUB</span></a></li><!-- 20220726 //-->
		</ul>
		<ul class="menu">
			<li class="menu__title"><span>인사이트</span></li>
			<li class="menu__link"><a href="./letter.html"><span>뉴스레터</span></a></li>
			<li class="menu__link"><a href="./report.html"><span>리포트</span></a></li>
			<li class="menu__link"><a href="./column.html"><span>광고컬럼</span></a></li>
		</ul>
		<ul class="menu">
			<li class="menu__title"><span>플레이디</span></li>
			<li class="menu__link"><a href="./about.html"><span>ABOUT</span></a></li> <!-- 20220615 -->
			<li class="menu__link"><a href="./ir.html"><span>IR</span></a></li>
			<li class="menu__link"><a href="./ethical.html"><span>윤리경영</span></a></li>
			<li class="menu__link"><a href="./esg.html"><span>ESG</span></a></li> <!-- 20220615 -->
		</ul>
		<ul class="menu">
			<li class="menu__title"><span>인재채용</span></li>
			<li class="menu__link"><a href="./recruit.html"><span>채용</span></a></li>
			<li class="menu__link"><a href="./welfare.html"><span>복리후생</span></a></li> <!-- 20220615 -->
		</ul>
		<ul class="menu">
			<li class="menu__title"><a href="./contact.html"><span>Contact</span></a></li>
		</ul>
	</div>
</div>