<!DOCTYPE html>
<html lang="ko_KR">
<head>
  <!--220627수정-->
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content="PlayD"/>
  <meta name="description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다"/>  
  <meta property="og:locale" content="ko_KR" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="PlayD" />
  <meta property="og:keywords" content="PlayD" />
  <meta property="og:description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다" />
  <meta property="og:url" content="http://playd.com" />
  <meta property="og:image" content="@@webroot/assets/images/common/sns_share.jpg">
  <meta property="og:site_name" content="PlayD" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다" />
  <meta name="twitter:title" content="PlayD" />
  <link rel="icon" href="@@webroot/assets/images/common/favicon.png" sizes="32x32" />
  <link rel="icon" href="@@webroot/assets/images/common/favicon.png" sizes="192x192" />
  <link rel="apple-touch-icon" href="" />
  
	<title>@@pagetitle</title>
	<link rel="stylesheet" href="@@webroot/assets/css/w/ui.css">
  <link rel="stylesheet" href="https://use.typekit.net/gjs0snj.css">

  
<!-- Head Logscript  Start -------------------------------------------------------------------------------------------------------->	


<!-- PlayD TERA Log Definition Script Start -->
<script>
window['_LA']=window['_LA']||function(){
   (window['_LA'].q=window['_LA'].q||[]).push(arguments)
}
</script>

<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-K9D4DP');</script>
<!--End Google Tag ManagerFacebook Pixel Code-->
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '1813814922182678'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1813814922182678&ev=PageView&noscript=1"
/></noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->

<!-- Head Logscript  End -------------------------------------------------------------------------------------------------------->	
</head>