<footer class="footer">
	<div class="section__inner">
			<p class="logo logo__footer"><a href="#"><span class="a11y">플레이디</span></a></p>
			<div class="footer__inner">
				<ul class="footer__util">
					<li>(주)플레이디</li>
					<li>사업자등록번호 : </li>
					<li>사업자등록번호 : </li>
					<li>사업자등록번호 : </li>
				</ul>
				<p class="copyright">Copyright©PlayD.,Ltd, All rights reserved.</p>
			</div>
	</div>
</footer>
<script src="@@webroot/assets/js/ui.js"></script>
