<footer class="footer">
  <div class="foo_row">
		<p class="foo_logo"><a href="#"><span class="a11y">playD</span></a></p>
		<div class="inn">
			<ul class="foo_util">
				<li>(주)플레이디</li>
				<li>사업자등록번호 : </li>
				<li>사업자등록번호 : </li>
				<li>사업자등록번호 : </li>
			</ul>
			<p class="copyright">Copyright©PlayD.,Ltd, All rights reserved.</p>
		</div>
	</div>
</footer>
<script src="/assets/js/ui.js"></script>