<!--220617 start-->
<div class="layer__body popup report" id="report" aria-hidden="true" role="dialog">
	<div class="layer__wrap layer__wrap--wide">
		<div class="layer__close">
			<button class="close"><span>close</span></button>
		</div>
		<div class="layer__inner">
			<div class="layer__head">
				<p class="content__title">PlayD 트렌드 리포트 다운로드</p>
				<p class="content__description">
					간단한 정보를 입력하시면 플레이디 리포트를 빠르게<br>
					받아보실 수 있습니다.
				</p>
			</div>
			<div class="layer__content">
				<div class="content__text">
					<form>
						<legend>플레이디 트렌드 리포트 다운로드 신청폼</legend>
						<div class="form-field">
							<label for="user-name" class="input-box-info__label input-box-info__label--necessary">이름</label>
							<input type="text" id="user-name"  class="input-box-info__input" name="" placeholder="이름을 입력해 주세요.">
							<p class="form-warning">이름을 입력해주세요.</p>
						</div>
						<div class="form-field">
							<label for="user-position" class="input-box-info__label input-box-info__label--necessary">직업</label>
							<input type="text" id="user-position" class="input-box-info__input" name="" placeholder="직업을 입력해 주세요.">
							<p class="form-warning">직업을 입력해 주세요.</p>
						</div>
						<div class="form-field">
							<label for="user-mail" class="input-box-info__label input-box-info__label--necessary">이메일 주소</label>
							<input type="text" id="user-mail"  class="input-box-info__input" name="" placeholder="이메일 주소를 입력해 주세요.">
							<p class="form-warning">이메일 주소를 입력해 주세요.</p>
						</div>
						<div class="form-field">
							<label for="user-position" class="input-box-info__label">직급</label>
							<input type="text" id="user-position" class="input-box-info__input" name="" placeholder="직급을 입력해 주세요.">
						</div>
						<div class="form-field">
							<label for="user-company" class="input-box-info__label">회사명(소속)</label>
							<input type="text" id="user-company" class="input-box-info__input" name="" placeholder="회사명을 입력해 주세요.">
						</div>
						<div class="form-field">
							<label for="user-team" class="input-box-info__label">부서(팀명)</label>
							<input type="text" id="user-team" class="input-box-info__input" name="" placeholder="부서를 입력해 주세요.">
						</div>
						<div class="sub-checkboxs">
							<label for="sub-checkbox--personal" class="sub-checkbox__label">
								<input type="checkbox" id="sub-checkbox--personal" name="" class="sub-checkbox__input" checked>
								<span>개인정보 수집 및 이용동의</span>
							</label>
						</div>
						<p class="form-description">
							입력하신 이름, 직업, 이메일 주소, 직급, 회사명
							(소속), 부서(팀명)은 뉴스레터 발송을 위해 정보주체로부터 개인정보를 수집시에 동의 받은 개인정보 
							보유,이용기간 동안 보관 및 이용됩니다.
						</p>
					</form>
				</div>
				<button type="submit" class="button layer__button form-submit--wide">리포트 다운로드</button>
			</div>
		</div>
	</div>
</div>
<!--220617 end-->


<!--220627 수정 start-->

<footer class="footer">
 <section class="footer__banner banner">
		<div class="banner__content">
			<p class="banner__title font--md">플레이디와 함께 멈추지 않는 성장을 경험하세요.</p>
			<div class="button__wrap">
				<a href="#" class="button__square button__lined-white font--bd">프로젝트 문의</a>
				<a href="#" class="button__square button__filled-white font--bd">회사 소개서 다운로드</a>
			</div>
		</div>
	</section>
	<div class="footer-top">
		<div class="footer-top__inner">
			<p class="logo logo__footer">
			<a href="#">
				<img src="../assets/images/m/common/logo_color.png" alt="플레이디 로고">
			</a>
			</p>
			<div class="footer__nav">
				<div class="footer__wrap footer__wrap--line">
					<p><a href="#">윤리신고</a></p>
					<p><a href="#">뉴스레터</a></p>
					<p><a href="#">오시는 길</a></p>
					<p class="footer__line--last"><a href="#">무료 광고 진단</a></p>
				</div>
				<div class="footer__wrap--line"><p class="footer__line--last"><a href="#" class="font--bd ">개인 정보처리 방침</a></p></div>
			</ul>
			<nav class="footer__nav--right">
				<a href="#" class=""><img src="../assets/images/m/common/logo_naver.png" /><span class="a11y">네이버</span></a>
				<a href="#" class=""><img src="../assets/images/m/common/logo_instagram.png" /><span class="a11y">인스타그램</span></a>
				<a href="#" class=""><img src="../assets/images/m/common/logo_youtube.png" /><span class="a11y">유투브</span></a>
				<a href="#" class=""><img src="../assets/images/m/common/logo_facebook.png" /><span class="a11y">페이스북</span></a>
			</nav>
		</div>
	</div>
	<div class="footer-bottom">
		<ul class="footer__util">
			<li>(주)플레이디</li>
			<li>대표자 : 이준용 | 사업자등록번호 : 129-86-43885</li>
			<li>주소 : 경기도 성남시 분당구 황새울로 359번 길 11, 5층</li>
			<li>이메일 : <a href="mailto:master@playd.com">master@playd.com</a></li>
			<li class="copyright">Copyright &copy; PlayD.,Ltd, All rights reserved.</li>
		</ul>
		<nav class="footer__util--right">
			<p class="information"><span class="information__title">대표전화</span><span class="footer__number numbering">1566-3265</span></p>
			<ul class="information__desc">
				<li>MON - FRI 09 : 00 - 18:00</li>
				<li>주말, 공휴일 휴무</li>
				<li>BREAK TIME : 12:30 - 13:30</li>
			</ul>
		</nav>
	</div>
</footer>


<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="@@webroot/assets/js/m/countUp.js"></script>
<script src="@@webroot/assets/js/m/swiper.min.js"></script>
<script src="@@webroot/assets/js/m/ui.js"></script>
<script src="@@webroot/assets/js/jquery-1.12.4.min.js"></script>

<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="@@webroot/assets/js/datepicker.js"></script>

<!--220627 수정 end-->




