<header id="header" class="header @@headertype">
	<button type="button" class="header__button">
		<span class="burger-sticks"></span>
		<span class="burger-sticks"></span>
		<span class="burger-sticks"></span>
	</button>
	<!--220704 수정 start-->
	<div class="header__inner header__inner--full">
		<h1 class="header__title">
			<a href="./index.html" class="logo logo__default"><span class="a11y">플레이디</span></a>
		</h1>
		<nav class="gnb">
			<p class="header__logo">
				<a href="./index.html" class="logo logo__default"><span class="a11y">플레이디</span></a>
			</p>
			<div class="gnb__list">
				<div class="gnb__item">
					<a href="./campaign.html" role="button" class="gnb__list--link font--bd">사업영역</a>
					<div class="gnb__wrap">
						<div class="gnb__box">
							<p><a href="./campaign.html">캠페인 전략</a></p><!--220627 수정-->
							<p><a href="./media.html">미디어전략</a></p>
							<p><a href="./creative.html">크리에이티브</a></p>
						</div>
						<p class="gnb__link--sub"><a href="./portfolio.html">포트폴리오</a></p>
						<p><a href="./awards.html">수상내역</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="./techhub.html" role="button" class="gnb__list--link font--bd">솔루션</a>
					<div class="gnb__wrap">
						<p><a href="./techhub.html">tech HUB</a></p><!--220726-->
					</div>
				</div>
				<div class="gnb__item">
					<a href="./letter.html" role="button" class="gnb__list--link font--bd">인사이트</a>
					<div class="gnb__wrap">
						<p><a href="./letter.html">뉴스레터</a></p>
						<p><a href="./report.html">리포트</a></p>
						<!-- <p><a href="./column.html">광고 칼럼</a></p>220627 수정 -->
					</div>
				</div>
				<div class="gnb__item">
					<a href="./about.html" role="button" class="gnb__list--link font--bd">플레이디</a>
					<div class="gnb__wrap">
						<p><a href="./about.html">ABOUT</a></p>
						<p><a href="./ir.html">IR</a></p>
						<p><a href="./ethical.html">윤리경영</a></p>
						<p><a href="./esg.html">ESG</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="./recruit.html" role="button" class="gnb__list--link font--bd">인재 채용</a><!--220627 수정-->
					<div class="gnb__wrap">
						<p><a href="./recruit.html">채용</a></p>
						<p><a href="./welfare.html">복리후생</a></p>
					</div>
				</div>
			</div>
			<p class="gnb__button"><a href="./contact.html" class="gnb__button--link">CONTACT</a></p>
		</nav>
	</div>
	<!--220704 수정 end-->
</header>