<header id="header" class="header @@headertype">
	<button type="button" class="header__button">
		<span class="burger-sticks"></span>
		<span class="burger-sticks"></span>
		<span class="burger-sticks"></span>
	</button>
	<div class="header__inner header__inner--full">
		<h1 class="header__title">
			<a href="#" class="logo logo__default"><span class="a11y">플레이디</span></a>
		</h1>
		<nav class="gnb">
			<div class="gnb__list">
				<div class="gnb__item">
					<a href="/" role="button" class="gnb__list--link font--bd">사업영역</a>
					<div class="gnb__wrap">
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">미디어전략</a></p>
						<p><a href="/">크리에이티브</a></p>
						<p><a href="/">포트폴리오</a></p>
						<p><a href="/">수상내역</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="/" role="button" class="gnb__list--link font--bd">솔루션</a>
					<div class="gnb__wrap">
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="/" role="button" class="gnb__list--link font--bd">인사이트</a>
					<div class="gnb__wrap">
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="/" role="button" class="gnb__list--link font--bd">플레이디</a>
					<div class="gnb__wrap">
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
					</div>
				</div>
				<div class="gnb__item">
					<a href="/" role="button" class="gnb__list--link font--bd">인재채용</a>
					<div class="gnb__wrap">
					<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
						<p><a href="/">캠페인전략</a></p>
					</div>
				</div>
			</div>
			<p class="gnb__button"><a href="/" class="gnb__button--link font--bd">CONTACT</a></p>
		</nav>
	</div>
	<link rel="stylesheet" href="https://use.typekit.net/gjs0snj.css">
	<link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css"> 
</header>