<!DOCTYPE html>
<html lang="ko_KR">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="keywords" content=""/>
  <meta name="description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다"/>  
  <meta property="og:locale" content="ko_KR" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="" />
  <meta property="og:keywords" content="" />
  <meta property="og:description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다" />
  <meta property="og:url" content="" />
  <meta property="og:site_name" content="PlayD" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:description" content="kt그룹 디지털마케팅 대행사 플레이디는 고객 성장에 필요한 모든 마케팅 서비스를 제공합니다" />
  <meta name="twitter:title" content="" />
  <link rel="icon" href="" sizes="32x32" />
  <link rel="icon" href="" sizes="192x192" />
  <link rel="apple-touch-icon" href="" />

	<title>@@pagetitle</title>
	<link rel="stylesheet" href="@@webroot/assets/css/m/ui.css">
  <link rel="stylesheet" href="https://use.typekit.net/gjs0snj.css">
	<link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css"> 
</head>